import NavBar from "@/components/common/navbar";

import "./globals.css";
import "/public/fonts/Line_Seed_Sans_TH/fonts.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <NavBar />
          <main className="max-w-5xl m-auto p-4">
            {children}
          </main>
        </body>
    </html>
  );
}
